### ISSUE TITLE
can DipAsm use on singularity?

### ISSUE THREAD

**Issue by masen1991** [shilpagarg/DipAsm#10]
Hello ,
Can DipAsm supported by singularity?
Because i can't use sudo to run docker,maybe you can add some workflow about how to use singularity to run DipAsm?
And also can the Hic input be .fq.gz?

**Comment by shilpagarg** [comment]
Please see #16

**Comment by masen1991** [comment]
i really do not know what u say .
so it can not work on  singularity?i can only use it from docker.right?
