### ISSUE TITLE
permission denied of installment

### ISSUE THREAD

**Issue by yanhaidong1** [shilpagarg/DipAsm#12]
Hi, I am trying to install DipAsm but i got stuck when I am using 'docker build -t dipasm . '. The error message is: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=zkolg6f11j9mkz4i03w0kefmb&shmsize=0&t=dipasm&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied. 
Thanks for the helping!!
Best wishes,
Haidong

**Comment by Ahahaha3** [comment]
you can ask your root to run this command:"sudo usermod -a -G docker $USER"
https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/

**Comment by yanhaidong1** [comment]
Thanks! I got it.
