### ISSUE TITLE
Can Dipasm be used for plant genomes？

### ISSUE THREAD

**Issue by Ahahaha3** [shilpagarg/DipAsm#13]
I have read a paper about this tool"Accurate chromosome-scale haplotype-resolved assembly of human genomes ". But i'm not  sure this tool could be used for plant genome, if i assembled a genome by hifiasm. In addition， I just want to use this tool to phase my genome. how to do this? Thanks a million!

**Comment by shilpagarg** [comment]
Please see #16

**Comment by shilpagarg** [comment]
Please email me properties of genome and datasets at shilpa.garg2k7@gmail.com. I will be happy to help.
