### ISSUE TITLE
DipAsm

### ISSUE THREAD

**Issue by duhuipeng** [shilpagarg/DipAsm#14]
Dear author
On the server, I installed DipAsm through the docker. I found out it needed three software 3D-DNA, hapsCut this process,However, I found that there is a software that has been unable to install, that is, Deepvariant,(I installed it through docker) it error is as follows
![image](https://user-images.githubusercontent.com/58722433/104998065-956bd180-5a65-11eb-83f3-9f3b9487b8ae.png)

What should I do to solve the problem
Looking forward to your reply

**Comment by shilpagarg** [comment]
Please see #16
