### ISSUE TITLE
The result of the run is returned, but "scaffold_connection.txt" is 0 in the result file

### ISSUE THREAD

**Issue by jenny315** [shilpagarg/DipAsm#18]
Dear Shilpagarg,

Thanks for the instructions. It finally got out. There is no error report in the log file.

1. One of the output files, "scaffold_connection.txt," is "0" and has nothing in it, I'm not sure if there's a problem.
2. I'm not sure what each file means. Whether "pred_hap1" and "pred_hap2" are the two sets of haplotypes, why are they so different? Is it normal? Is it because the heterozygosity (approximate 1.3%) is not high enough?
3. And most importantly, I'm not sure how to validate, evaluate or improve these two haplotypes.

8 files were generated as a result of the run，as shown below (The "1pst_" tag was added when I modified the file name)
```
-rw-r--r-- 1 jenny JJ  20G Jan 29 23:27 1pst_hic_name_connection.output
-rw-r--r-- 1 jenny JJ 877M Jan 30 01:30 1pst_pred_broken_nodes.fa
-rw-r--r-- 1 jenny JJ 805M Jan 30 06:15 1pst_pred_hap1.fa
-rw-r--r-- 1 jenny JJ  81M Jan 30 06:15 1pst_pred_hap2.fa
-rw-r--r-- 1 jenny JJ 1.6G Jan 30 01:30 1pst_pred_haplotypes.fa
-rw-r--r-- 1 jenny JJ  58M Jan 30 06:15 1pst_scaff_connections.txt
-rw-r--r-- 1 jenny JJ   0 Jan 30 01:30 1pst_scaffold_connection.txt
-rw-r--r-- 1 jenny JJ  515 Jan 30 06:15 1pst_scaffold_result_reordered.txt
```
Thanks for any advice,
Best regards,
Jenny

**Comment by shilpagarg** [comment]
Thanks for getting back. The run seems to be successful :). Yes, hap1 and hap2 are two haplotypes. You may wanna concatenate brokeb_nodes.fa to hap2. Yes, I could potentially help to further validate these sequences if you could send me an email.

**Comment by jenny315** [comment]
Dear Shilpagarg,

Many thanks for your prompt response.
I sent an email to  shilpa.garg2k7@gmail.com, is this it? . 

Thanks for any advice,
Best regards,
Jenny
