### ISSUE TITLE
Pstools pre_hap1 or pre_hap2

### ISSUE THREAD

**Issue by zhoudreames** [shilpagarg/DipAsm#21]
i got a problem by using pstools,the length of scaffold0l_hap1 and scaffold1l_hap2 is very long in pre_hap1.fa file ,longer than expected the true length of  chromosome (<200Mb) ,however, the pre_hap2.fa file split scaffold0l_hap1/scaffold1l_hap2  into different smaller scaffolds.thoes result show in blew,i dont why ,could you help me ,thanks~
![image](https://user-images.githubusercontent.com/54714639/107164826-94d2b500-69eb-11eb-85df-29cdc4ca972f.png)
![image](https://user-images.githubusercontent.com/54714639/107164841-a6b45800-69eb-11eb-99a4-abb5d7fd3497.png)

**Comment by zhoudreames** [comment]
@lh3 @cschin @eldariont @shilpagarg

**Comment by shilpagarg** [comment]
Thank you for your patience. I am working on your request and will provide a general update for non-human assemblies soon. Hope this works.

**Comment by zhoudreames** [comment]
> Thank you for your patience. I am working on your request and will provide a general update for non-human assemblies soon. Hope this works.

thank you for your reply~looking forward to your updates

**Comment by shilpagarg** [comment]
Please try purge_dups by Richard, Shane, Dengfeng et al.

**Comment by zhoudreames** [comment]
> Thank you for your patience. I am working on your request and will provide a general update for non-human assemblies soon. Hope this works.
when you development non-human assemblies by pstools? thanks!
